### ISSUE TITLE
Server not running

### ISSUE THREAD

**Issue by Fcsteve777** [craigmw/CellarWarden#12]
I hope im not bringing this back from the dead but it looks like it would be a good way to control 2 meat curing chambers via the Pi. Im currently having issues getting the server up and im wondering if its me or compatibility issues. 

I have Raspbipan buster on the pi 3 i have and have followed up with the install instructions. i found issue 4 and went off of that because i received many warnings and errors when trying to install the newest version of node.
when installing node i used the following:
wget http://nodejs.org/dist/v4.4.2/node-v4.4.2-linux-armv7l.tar.gz
tar -xvf node-v4.4.2-linux-armv7l.tar.gz
cd node-v4.4.2-linux-armv7l
sudo cp -R * /usr/local/
sudo reboot

when i then use node -v and npm -v i see that they are both installed
Then when i install cellarwarden per the rest of the tutorial the server wont start and i get a "cant find module error"

Is this something to do with me needing to rename another file due to the node directory that i am targeting? Or target a different directory so cellarwarden and node work together correctly?

or is there a user issue? I never changed the user name but set a password on the Pi does the "sudo cp -R * /usr/local/" line need to change?

Sorry in advance for my ignorance!
Steven

**Comment by craigmw** [comment]
Steven:

CellarWarden is configured to run from node.js installed by the root user. So, it is expecting to find node in the root home directory. You could try uninstalling node.js from the /home/pi directory, logging in as root and then installing it again. Alternatively, you could try to adjust your rc.local file to point to the correct directory that you've installed node.js into. There is more information here about how to set up an environmental variable to make access to node.js global, in which case, the rc.local file would not need to point to the root user:

https://imcodebased.com/node-js-error-cannot-find-module-solved/

**Comment by Fcsteve777** [comment]
Up and running! Installed in the root home directory as you said. i also had to use "sudo npm install" to get CellarW to install properly.

Time to buy some sensors. Thank you for the help
Steven

**Comment by craigmw** [comment]
Best of luck! I look forward to hearing how it works for you.

Craig

**Comment by specka123** [comment]
> Steven:
> 
> CellarWarden is configured to run from node.js installed by the root user. So, it is expecting to find node in the root home directory. You could try uninstalling node.js from the /home/pi directory, logging in as root and then installing it again. Alternatively, you could try to adjust your rc.local file to point to the correct directory that you've installed node.js into. There is more information here about how to set up an environmental variable to make access to node.js global, in which case, the rc.local file would not need to point to the root user:
> 
> https://imcodebased.com/node-js-error-cannot-find-module-solved/

Hi Guys - I am trying to get this working also, and ran into problems with node and npm installation, due to the errors thrown when I tried to do it. I guess a lot of this is very out of date and deprecated but should the application still work? 

I tried using the commands listed in Fcsteve777 post:
wget http://nodejs.org/dist/v4.4.2/node-v4.4.2-linux-armv7l.tar.gz
tar -xvf node-v4.4.2-linux-armv7l.tar.gz
cd node-v4.4.2-linux-armv7l
sudo cp -R * /usr/local/
sudo reboot

This doesnt seem to have solved it - I cannot see node processes running and I cannot access the web interface via <ip address>:8888

Any help would be greatly appreciated.

Thank you

EDIT: Im using a Pi 3B and latest version of Raspberry Pi OS. I have not yet connected sensors.

**Comment by specka123** [comment]
I seem to be stuck with the node and npm versioning. If I use the wget method and unpack to root/home directory, I guess there must be a command needed to "install" the packages? Following fcsteve777 commands I only see an upack and then cp command.

Following the official instructions, the commands below result in deprecation warnings and I end up with version 10 of node installed. I cant seem to prevent that occurring.

**_curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -
sudo apt-get install -y build-essential python-dev nodejs npm_**

Unsure how to get past this problem.

**Comment by specka123** [comment]
Im guessing everything is just deprecated to the extent it no longer works.

https://pastebin.com/Fug0zaGC

**Comment by craigmw** [comment]
It is not depricated. I continue to use this on my own wine cellar and fermentation chamber. I have not tested it for more recent versions of Raspian, and I will eventually do so. You can certainly try it using the lNode version listed in the Readme. However, often such incompatibilities are due to underlying extensions no longer being supported by their authors. I will look into this.

**Comment by specka123** [comment]
Hi Craig - thanks for replying. Yes I did mean that the dependencies/extensions are deprecated rather than your software itself.

I am also definitely not ruling out user error, I can normally get by enough to get things to work it just takes me an inordinate amount of time. But in this case i was worried I could be 'flogging a dead horse' if it requires updates to the code itself. I'll keep an eye out for any updates. I'm very keen to get this up and running. I would be happy to make a donation for your effort.
