### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by n781td** [craigmw/CellarWarden#9]
I am new to the RaspPi and just recently got CellarWarden installed and working with a couple temp sensors (DHT22 and OW probe). Next I would like to experiment with controlling the compressor of a mini fridge to maintain temperature. I was originally just going to switch on and off a solid-state relay but it looks like CellarWarden requires a PID or hysteresis protocol. Do you have any recommendations on devices that were intended to be used with this software for controlling a cooling/heating unit?

**Comment by craigmw** [comment]
CellarWarden will do what you want it to. You just need to hook up an SSR or relay board to a GPIO pin on the RPi to do so. For a compressor, I'd recommend getting a Sainsmart 2 channel relay board (https://www.sainsmart.com/arduino-pro-mini.html) and using hysteresis control to maintain your fridge temperature. The Sainsmart board is nice because it can be connected to the 3.3V GPIOs on an RPi, but is powered by the 5V pin on the RPi. More info about interfacing relays with the RPi is available here:

https://tech.iprock.com/?p=10030

**Comment by n781td** [comment]
Hello,

Thank you for your quick reply and for sending those links, I understand how the controller needs to be interfaced to the relay now.
Regarding the Alarms config page; do you have docs showing how the SMTP function is working? I can’t get it to work with either my Gmail or Outlook.com (formerly Hotmail) accounts. I’m curious what ports are being used, if SSL is enabled, etc. Thank you! You have written a really neat program.


Trevor Conroy

**Comment by craigmw** [comment]
Hi Trevor:

CellarWarden uses NodeMailer ([https://github.com/nodemailer/nodemailer](url)) to send text and email messages. You might check out their examples for more details about this. They mention that sometimes Gmail works and sometimes it doesn't. I'm using a Gmail account to send SMS and email messages, so it seems to work for me. You need to make sure that your password to your sending account is working okay. If you can't get it to work from Gmail, maybe you can set up a Yahoo mail account and see if that works.

**Comment by n781td** [comment]
Hi Craig,

I read through the Node Mailer docs and found the list of common email services. On a hunch I entered 'Gmail' (rather than the actual SMTP host name) in the Email Service field on the Alarms dialog and it started working. I looked through the NodeMailer folder within CellarWarden and found a common services file that has the listing of email services but it's not the same as on the Node Mailer website (they have an entry for Office365 among others). Is that file the one CellarWarden actually references or is it located somewhere else? I'd like to update it with the current listing provided on the NodeMailer website.

Also, I got a 40amp SSR connected through a transistor to provide it 5V and it's working great in Hysteresis mode! I'm a bit perplexed though as to the difference between the 'Control Mode: Hysteresis' box and the 'Delay: ' box. They both seem to function as a method of preventing quick cycling of the control actuator. Can you explain a little more as to how those two features work interdependently?

Thanks,
Trevor

Sent from my iPhone

On May 29, 2017, at 8:40 AM, craigmw <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Trevor:

CellarWarden uses NodeMailer https://github.com/nodemailer/nodemailer<url> to send text and email messages. You might check out their examples for more details about this. They mention that sometimes Gmail works and sometimes it doesn't. I'm using a Gmail account to send SMS and email messages, so it seems to work for me. You need to make sure that your password to your sending account is working okay. If you can't get it to work from Gmail, maybe you can set up a Yahoo mail account and see if that works.

**Comment by craigmw** [comment]
Trevor:

I'm glad to hear you found this, though the help page for Alarms does show "Gmail" as an example for that field. Unfortunately, the docs for nodemailer are lacking, so not much help there. 

The Delay parameter simply provides a way to prevent the actuator from turning on for a set delay from the last time it turned off to prevent rapid cycling. On my chest freezer, I set this to 10 (minutes). Incidentally, the delay is independent of the type of control; it works in both PID and hysteresis modes. The Hysteresis parameter sets the temperature band around which the temperature can vary. For my chest freezer, I set this to 2F. These will interact in hysteresis mode, but since I don't mind a bit of temperature variation around my setpoint (32-34F), this is the range I set it at. The Delay simply ensures that my compressor is not cycled more than once every ten minutes to reduce wear on it over time. This also allows me to use a standard mechanical relay to switch it, again considering that rapid cycling would destroy a mechanical relay in short order. There is additional info about this in the Controllers help screen.
